export enum FOLDER_NAMES {
  IMAGE = "image",
  SEATING_VIEW = "seatingView",
  PROFILE_IMAGE = "profileImage",
  THUMBNAIL = "thumbnail",
  PARCEL_PHOTOS = "parcelPhotos",
  ATTACHMENTS = "attachments",
  VEHICLE_IMAGE = "vehicleImage",
  VEHICLE_REGISTRATION_DOC = "vehicleRegistrationDoc",
  STATE_ID_DOC = "stateIdDoc",
  DRIVERS_LICENSE_DOC = "driversLicenseDoc",
  SSN_DOC = "ssnDoc",
  INSURANCE_DOC = "insuranceDoc",
  OTHERS = "others",
  REMOVE_IMAGE = "removeImage",
}